// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsmouwqmwazwdsyqtnlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzbW91d3Ftd2F6d2RzeXF0bmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODg2MTUsImV4cCI6MjA3MjQ2NDYxNX0.Me1ngh9mE952Nni7rcsMzArpAEglJ9c8sMQtioCsfYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});